services:
  k6:
    image: grafana/k6:latest
    user: root

    ports:
      - "5665:5665"

    volumes:
      - ./tests:/scripts
      - ./reports:/reports

    working_dir: /scripts

    extra_hosts:
      - "host.docker.internal:host-gateway"

    env_file:
      - .env    

    entrypoint: ["sh", "-c"]
    command:
      - k6 run $${SCRIPT} --summary-export=/reports/summary.json